#pragma once

/*
* Keyboard Inputs as in SDL_scancode.h - This is just a layering on top of it.
* TODO: If other platforms are going to be added to the engine, this has to change according to the platform.
*/

namespace PeanutButter {
	typedef enum {
        PB_KEYCODE_UNKNOWN = 0,
        PB_KEYCODE_A = 4,
        PB_KEYCODE_B = 5,
        PB_KEYCODE_C = 6,
        PB_KEYCODE_D = 7,
        PB_KEYCODE_E = 8,
        PB_KEYCODE_F = 9,
        PB_KEYCODE_G = 10,
        PB_KEYCODE_H = 11,
        PB_KEYCODE_I = 12,
        PB_KEYCODE_J = 13,
        PB_KEYCODE_K = 14,
        PB_KEYCODE_L = 15,
        PB_KEYCODE_M = 16,
        PB_KEYCODE_N = 17,
        PB_KEYCODE_O = 18,
        PB_KEYCODE_P = 19,
        PB_KEYCODE_Q = 20,
        PB_KEYCODE_R = 21,
        PB_KEYCODE_S = 22,
        PB_KEYCODE_T = 23,
        PB_KEYCODE_U = 24,
        PB_KEYCODE_V = 25,
        PB_KEYCODE_W = 26,
        PB_KEYCODE_X = 27,
        PB_KEYCODE_Y = 28,
        PB_KEYCODE_Z = 29,

        PB_KEYCODE_1 = 30,
        PB_KEYCODE_2 = 31,
        PB_KEYCODE_3 = 32,
        PB_KEYCODE_4 = 33,
        PB_KEYCODE_5 = 34,
        PB_KEYCODE_6 = 35,
        PB_KEYCODE_7 = 36,
        PB_KEYCODE_8 = 37,
        PB_KEYCODE_9 = 38,
        PB_KEYCODE_0 = 39,

        PB_KEYCODE_RETURN = 40,
        PB_KEYCODE_ESCAPE = 41,
        PB_KEYCODE_BACKSPACE = 42,
        PB_KEYCODE_TAB = 43,
        PB_KEYCODE_SPACE = 44,

        PB_KEYCODE_MINUS = 45,
        PB_KEYCODE_EQUALS = 46,
        PB_KEYCODE_LEFTBRACKET = 47,
        PB_KEYCODE_RIGHTBRACKET = 48,
        PB_KEYCODE_BACKSLASH = 49,
        PB_KEYCODE_NONUSHASH = 50,
        PB_KEYCODE_SEMICOLON = 51,
        PB_KEYCODE_APOSTROPHE = 52,
        PB_KEYCODE_GRAVE = 53, 
        PB_KEYCODE_COMMA = 54,
        PB_KEYCODE_PERIOD = 55,
        PB_KEYCODE_SLASH = 56,

        PB_KEYCODE_CAPSLOCK = 57,

        PB_KEYCODE_F1 = 58,
        PB_KEYCODE_F2 = 59,
        PB_KEYCODE_F3 = 60,
        PB_KEYCODE_F4 = 61,
        PB_KEYCODE_F5 = 62,
        PB_KEYCODE_F6 = 63,
        PB_KEYCODE_F7 = 64,
        PB_KEYCODE_F8 = 65,
        PB_KEYCODE_F9 = 66,
        PB_KEYCODE_F10 = 67,
        PB_KEYCODE_F11 = 68,
        PB_KEYCODE_F12 = 69,

        PB_KEYCODE_PRINTSCREEN = 70,
        PB_KEYCODE_SCROLLLOCK = 71,
        PB_KEYCODE_PAUSE = 72,
        PB_KEYCODE_INSERT = 73, 
        PB_KEYCODE_HOME = 74,
        PB_KEYCODE_PAGEUP = 75,
        PB_KEYCODE_DELETE = 76,
        PB_KEYCODE_END = 77,
        PB_KEYCODE_PAGEDOWN = 78,
        PB_KEYCODE_RIGHT = 79,
        PB_KEYCODE_LEFT = 80,
        PB_KEYCODE_DOWN = 81,
        PB_KEYCODE_UP = 82,

        PB_KEYCODE_NUMLOCKCLEAR = 83,
        PB_KEYCODE_KP_DIVIDE = 84,
        PB_KEYCODE_KP_MULTIPLY = 85,
        PB_KEYCODE_KP_MINUS = 86,
        PB_KEYCODE_KP_PLUS = 87,
        PB_KEYCODE_KP_ENTER = 88,
        PB_KEYCODE_KP_1 = 89,
        PB_KEYCODE_KP_2 = 90,
        PB_KEYCODE_KP_3 = 91,
        PB_KEYCODE_KP_4 = 92,
        PB_KEYCODE_KP_5 = 93,
        PB_KEYCODE_KP_6 = 94,
        PB_KEYCODE_KP_7 = 95,
        PB_KEYCODE_KP_8 = 96,
        PB_KEYCODE_KP_9 = 97,
        PB_KEYCODE_KP_0 = 98,
        PB_KEYCODE_KP_PERIOD = 99,

        PB_KEYCODE_NONUSBACKSLASH = 100,
        PB_KEYCODE_APPLICATION = 101,
        PB_KEYCODE_POWER = 102,
        PB_KEYCODE_KP_EQUALS = 103,
        PB_KEYCODE_F13 = 104,
        PB_KEYCODE_F14 = 105,
        PB_KEYCODE_F15 = 106,
        PB_KEYCODE_F16 = 107,
        PB_KEYCODE_F17 = 108,
        PB_KEYCODE_F18 = 109,
        PB_KEYCODE_F19 = 110,
        PB_KEYCODE_F20 = 111,
        PB_KEYCODE_F21 = 112,
        PB_KEYCODE_F22 = 113,
        PB_KEYCODE_F23 = 114,
        PB_KEYCODE_F24 = 115,
        PB_KEYCODE_EXECUTE = 116,
        PB_KEYCODE_HELP = 117,
        PB_KEYCODE_MENU = 118,
        PB_KEYCODE_SELECT = 119,
        PB_KEYCODE_STOP = 120,
        PB_KEYCODE_AGAIN = 121,
        PB_KEYCODE_UNDO = 122,
        PB_KEYCODE_CUT = 123,
        PB_KEYCODE_COPY = 124,
        PB_KEYCODE_PASTE = 125,
        PB_KEYCODE_FIND = 126,
        PB_KEYCODE_MUTE = 127,
        PB_KEYCODE_VOLUMEUP = 128,
        PB_KEYCODE_VOLUMEDOWN = 129,
    /* not sure whether there's a reason to enable these */
    /*     PB_KEYCODE_LOCKINGCAPSLOCK = 130,  */
    /*     PB_KEYCODE_LOCKINGNUMLOCK = 131, */
    /*     PB_KEYCODE_LOCKINGSCROLLLOCK = 132, */
        PB_KEYCODE_KP_COMMA = 133,
        PB_KEYCODE_KP_EQUALSAS400 = 134,

        PB_KEYCODE_INTERNATIONAL1 = 135,
        PB_KEYCODE_INTERNATIONAL2 = 136,
        PB_KEYCODE_INTERNATIONAL3 = 137, /**< Yen */
        PB_KEYCODE_INTERNATIONAL4 = 138,
        PB_KEYCODE_INTERNATIONAL5 = 139,
        PB_KEYCODE_INTERNATIONAL6 = 140,
        PB_KEYCODE_INTERNATIONAL7 = 141,
        PB_KEYCODE_INTERNATIONAL8 = 142,
        PB_KEYCODE_INTERNATIONAL9 = 143,
        PB_KEYCODE_LANG1 = 144, /**< Hangul/English toggle */
        PB_KEYCODE_LANG2 = 145, /**< Hanja conversion */
        PB_KEYCODE_LANG3 = 146, /**< Katakana */
        PB_KEYCODE_LANG4 = 147, /**< Hiragana */
        PB_KEYCODE_LANG5 = 148, /**< Zenkaku/Hankaku */
        PB_KEYCODE_LANG6 = 149, /**< reserved */
        PB_KEYCODE_LANG7 = 150, /**< reserved */
        PB_KEYCODE_LANG8 = 151, /**< reserved */
        PB_KEYCODE_LANG9 = 152, /**< reserved */

        PB_KEYCODE_ALTERASE = 153, /**< Erase-Eaze */
        PB_KEYCODE_SYSREQ = 154,
        PB_KEYCODE_CANCEL = 155,
        PB_KEYCODE_CLEAR = 156,
        PB_KEYCODE_PRIOR = 157,
        PB_KEYCODE_RETURN2 = 158,
        PB_KEYCODE_SEPARATOR = 159,
        PB_KEYCODE_OUT = 160,
        PB_KEYCODE_OPER = 161,
        PB_KEYCODE_CLEARAGAIN = 162,
        PB_KEYCODE_CRSEL = 163,
        PB_KEYCODE_EXSEL = 164,

        PB_KEYCODE_KP_00 = 176,
        PB_KEYCODE_KP_000 = 177,
        PB_KEYCODE_THOUSANDSSEPARATOR = 178,
        PB_KEYCODE_DECIMALSEPARATOR = 179,
        PB_KEYCODE_CURRENCYUNIT = 180,
        PB_KEYCODE_CURRENCYSUBUNIT = 181,
        PB_KEYCODE_KP_LEFTPAREN = 182,
        PB_KEYCODE_KP_RIGHTPAREN = 183,
        PB_KEYCODE_KP_LEFTBRACE = 184,
        PB_KEYCODE_KP_RIGHTBRACE = 185,
        PB_KEYCODE_KP_TAB = 186,
        PB_KEYCODE_KP_BACKSPACE = 187,
        PB_KEYCODE_KP_A = 188,
        PB_KEYCODE_KP_B = 189,
        PB_KEYCODE_KP_C = 190,
        PB_KEYCODE_KP_D = 191,
        PB_KEYCODE_KP_E = 192,
        PB_KEYCODE_KP_F = 193,
        PB_KEYCODE_KP_XOR = 194,
        PB_KEYCODE_KP_POWER = 195,
        PB_KEYCODE_KP_PERCENT = 196,
        PB_KEYCODE_KP_LESS = 197,
        PB_KEYCODE_KP_GREATER = 198,
        PB_KEYCODE_KP_AMPERSAND = 199,
        PB_KEYCODE_KP_DBLAMPERSAND = 200,
        PB_KEYCODE_KP_VERTICALBAR = 201,
        PB_KEYCODE_KP_DBLVERTICALBAR = 202,
        PB_KEYCODE_KP_COLON = 203,
        PB_KEYCODE_KP_HASH = 204,
        PB_KEYCODE_KP_SPACE = 205,
        PB_KEYCODE_KP_AT = 206,
        PB_KEYCODE_KP_EXCLAM = 207,
        PB_KEYCODE_KP_MEMSTORE = 208,
        PB_KEYCODE_KP_MEMRECALL = 209,
        PB_KEYCODE_KP_MEMCLEAR = 210,
        PB_KEYCODE_KP_MEMADD = 211,
        PB_KEYCODE_KP_MEMSUBTRACT = 212,
        PB_KEYCODE_KP_MEMMULTIPLY = 213,
        PB_KEYCODE_KP_MEMDIVIDE = 214,
        PB_KEYCODE_KP_PLUSMINUS = 215,
        PB_KEYCODE_KP_CLEAR = 216,
        PB_KEYCODE_KP_CLEARENTRY = 217,
        PB_KEYCODE_KP_BINARY = 218,
        PB_KEYCODE_KP_OCTAL = 219,
        PB_KEYCODE_KP_DECIMAL = 220,
        PB_KEYCODE_KP_HEXADECIMAL = 221,

        PB_KEYCODE_LCTRL = 224,
        PB_KEYCODE_LSHIFT = 225,
        PB_KEYCODE_LALT = 226, /**< alt, option */
        PB_KEYCODE_LGUI = 227, /**< windows, command (apple), meta */
        PB_KEYCODE_RCTRL = 228,
        PB_KEYCODE_RSHIFT = 229,
        PB_KEYCODE_RALT = 230, /**< alt gr, option */
        PB_KEYCODE_RGUI = 231, /**< windows, command (apple), meta */

        PB_KEYCODE_MODE = 257,    /**< I'm not sure if this is really not covered
                                     *   by any of the above, but since there's a
                                     *   special KMOD_MODE for it I'm adding it here
                                     */

        PB_KEYCODE_AUDIONEXT = 258,
        PB_KEYCODE_AUDIOPREV = 259,
        PB_KEYCODE_AUDIOSTOP = 260,
        PB_KEYCODE_AUDIOPLAY = 261,
        PB_KEYCODE_AUDIOMUTE = 262,
        PB_KEYCODE_MEDIASELECT = 263,
        PB_KEYCODE_WWW = 264,
        PB_KEYCODE_MAIL = 265,
        PB_KEYCODE_CALCULATOR = 266,
        PB_KEYCODE_COMPUTER = 267,
        PB_KEYCODE_AC_SEARCH = 268,
        PB_KEYCODE_AC_HOME = 269,
        PB_KEYCODE_AC_BACK = 270,
        PB_KEYCODE_AC_FORWARD = 271,
        PB_KEYCODE_AC_STOP = 272,
        PB_KEYCODE_AC_REFRESH = 273,
        PB_KEYCODE_AC_BOOKMARKS = 274,

        PB_KEYCODE_BRIGHTNESSDOWN = 275,
        PB_KEYCODE_BRIGHTNESSUP = 276,
        PB_KEYCODE_DISPLAYSWITCH = 277, 
        PB_KEYCODE_KBDILLUMTOGGLE = 278,
        PB_KEYCODE_KBDILLUMDOWN = 279,
        PB_KEYCODE_KBDILLUMUP = 280,
        PB_KEYCODE_EJECT = 281,
        PB_KEYCODE_SLEEP = 282,

        PB_KEYCODE_APP1 = 283,
        PB_KEYCODE_APP2 = 284,

        PB_KEYCODE_AUDIOREWIND = 285,
        PB_KEYCODE_AUDIOFASTFORWARD = 286,

        SDL_NUM_SCANCODES = 512 /**< not a key, just marks the number of scancodes
                                     for array bounds */
    } PB_Keycode;
}